
GET http://localhost:8000/todos
###

POST http://localhost:8000/books
###

GET http://localhost:8000/books/id-123
###

POST http://localhost:8000/todos
Content-Type: application/json

{ "id": 3, "name": "Client-Side Development", "done": true }

###

PUT http://localhost:8000/todos
Content-Type: application/json

{"todos": 40}
###

DELETE http://localhost:8000/books/id-348/comments/cmt-123
#Content-Type: application/json
#
#{"id":2}

###

GET https://simple-joke-api.deno.dev/random
###